apiVersion: v2
name: customer-api
description: Meridian Customer API - Helm Chart for Octopus Deploy
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Meridian Team
    email: team@meridian.example.com
